include:
  - local: .gitlab-ci-cloud.yml

mirror_to_cloud:
  stage: .post
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  script:
    - git remote add gitlab-cloud $(git remote get-url origin | sed 's/scovil.labtau.com/gitlab.com/g' | sed 's|ccvass/|allwiya/ccvass/|') || true
    - git push gitlab-cloud HEAD:main --force
  only:
    - main
  allow_failure: true
